steps:
    # build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/<PROJECT_ID>/locust-tasks:latest", "docker-image/."]
    # push container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/<PROJECT_ID>/locust-tasks:latest"]
    # deploy container image to GKE
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
    - run
    - --filename=kubernetes-config
    - --image=gcr.io/<PROJECT_ID>/locust-tasks:latest
    - --location=europe-west1
    - --cluster=locust-gke